CREATE TABLE post (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	authorId INT UNSIGNED NOT NULL,
	content VARCHAR(280),
	votes INT DEFAULT 0,
	age DATETIME,
	PRIMARY KEY (id)
);

CREATE TABLE author (
	authorId INT UNSIGNED NOT NULL,
	rejectedPosts INT NOT NULL DEFAULT 0,
	unban DATE DEFAULT '0000-00-00',
	PRIMARY KEY (authorId)
);

CREATE TABLE polarPopCount (
	id INT,
	value INT UNSIGNED,
	PRIMARY KEY (id)
);
